source 'https://github.com/readium/podspecs'
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'

  # Readium EPUB reader (updated for Swift 6 compatibility)
  pod 'ReadiumShared', '~> 3.6.0'
  pod 'ReadiumStreamer', '~> 3.6.0'
  pod 'ReadiumNavigator', '~> 3.6.0'
  pod 'ReadiumAdapterGCDWebServer', '~> 3.6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'

      # Force Swift 5 language mode for SwiftSoup to avoid Swift 6 syntax errors
      if target.name == 'SwiftSoup'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY'] = 'NO'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
        # Use Swift 5 language mode
        config.build_settings['SWIFT_LANGUAGE_VERSION'] = '5'
        config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -swift-version 5'
      end
    end
  end
end

