package com.retro99.statistics.domain.usecase

import com.retro99.base.result.CompletableResult
import com.retro99.reader.domain.model.BookType
import com.retro99.statistics.domain.StatisticsRepository
import com.retro99.statistics.domain.model.ReadingSessionDomainModel
import org.koin.core.annotation.Factory
import org.koin.core.annotation.Provided

/**
 * Use case for saving a reading session.
 */
@Factory
class SaveReadingSessionUseCase(
    @Provided private val repository: StatisticsRepository,
) {
    suspend operator fun invoke(
        bookUuid: String,
        bookTitle: String,
        bookType: BookType,
        startTime: Long,
        endTime: Long,
        durationMs: Long,
        pagesRead: Int? = null,
        startProgression: Double? = null,
        endProgression: Double? = null,
    ): CompletableResult {
        val session = ReadingSessionDomainModel(
            id = 0, // Will be auto-generated by the database
            bookUuid = bookUuid,
            bookTitle = bookTitle,
            bookType = bookType,
            startTime = startTime,
            endTime = endTime,
            durationMs = durationMs,
            pagesRead = pagesRead,
            startProgression = startProgression,
            endProgression = endProgression,
        )
        return repository.saveReadingSession(session)
    }
}

